### ISSUE TITLE
Cannot init a basic map.

### ISSUE THREAD

**Issue by konstantinberlin** [OpenHFT/Koloboke#37]
Hi,

I have download the 0.6.6 java 8 api files, and wrote this one line java main class which I took from the documentation example

package test2;

import java.util.Map;

import net.openhft.koloboke.collect.map.hash.HashIntIntMaps;

public class Try
{
	public static void main(String[] args)
	{
		Map<Integer, Integer> map = HashIntIntMaps.newMutableMap();

	}

}

I get this compiler error
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.openhft.koloboke.collect.map.hash.HashIntIntMaps.getDefaultFactory(HashIntIntMaps.java:52)
	at net.openhft.koloboke.collect.map.hash.HashIntIntMaps.newMutableMap(HashIntIntMaps.java:76)
	at test2.Try.main(Try.java:11)
Caused by: java.util.NoSuchElementException
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:365)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at net.openhft.koloboke.collect.map.hash.HashIntIntMaps$DefaultFactoryHolder.<clinit>(HashIntIntMaps.java:37)
	... 3 more

**Comment by leventov** [comment]
@konstantinberlin you should also have to have `-impl` jar in classpath. This Exception means API couldn't find any implementation.

**Comment by dbf256** [comment]
I've added

        <dependency>
            <groupId>com.koloboke</groupId>
            <artifactId>koloboke-compile</artifactId>
            <version>0.5.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.koloboke</groupId>
            
            <artifactId>koloboke-impl-common-jdk8</artifactId>
            <version>1.0.0</version>
        </dependency>
to my pom.xml
as an example in readme and for

public final HashIntObjMap users = HashIntObjMaps.newMutableMap();

I have

java.lang.ExceptionInInitializerError
	at com.koloboke.collect.map.hash.HashIntObjMaps.getDefaultFactory(HashIntObjMaps.java:55)
	at com.koloboke.collect.map.hash.HashIntObjMaps.newMutableMap(HashIntObjMaps.java:79)
	at travel.Storage.<init>(Storage.java:22)
	at travel.Main.<clinit>(Main.java:66)
Caused by: java.util.NoSuchElementException
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:365)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.koloboke.collect.map.hash.HashIntObjMaps$DefaultFactoryHolder.<clinit>(HashIntObjMaps.java:39)
	... 4 more
Exception in thread "main" 

Is it something wrong with my setup?
